# Generated by Django 5.1.4 on 2026-07-11 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_refactor_scheduled_wish'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='scheduledwish',
            new_name='core_schedu_contact_155163_idx',
            old_name='core_schedu_contact_b15b3e_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduledwish',
            new_name='core_schedu_status_0a5c77_idx',
            old_name='core_schedu_status_ef0c16_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduledwish',
            new_name='core_schedu_date_8f153b_idx',
            old_name='core_schedu_date_027bc9_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduledwish',
            new_name='core_schedu_user_id_6579b1_idx',
            old_name='core_schedu_user_id_4dbcb7_idx',
        ),
        migrations.AddField(
            model_name='scheduledwish',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelled At'),
        ),
        migrations.AddField(
            model_name='scheduledwish',
            name='delivery_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Delivery Status'),
        ),
        migrations.AddField(
            model_name='scheduledwish',
            name='email_subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email Subject'),
        ),
        migrations.AddField(
            model_name='scheduledwish',
            name='is_ai_generated',
            field=models.BooleanField(default=True, verbose_name='Is AI Generated'),
        ),
        migrations.AddField(
            model_name='scheduledwish',
            name='language',
            field=models.CharField(default='en', max_length=10, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='scheduledwish',
            name='last_error',
            field=models.TextField(blank=True, null=True, verbose_name='Last Error'),
        ),
        migrations.AddField(
            model_name='scheduledwish',
            name='notification_type',
            field=models.CharField(default='Email', max_length=20, verbose_name='Notification Type'),
        ),
        migrations.AddField(
            model_name='scheduledwish',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Opened At'),
        ),
        migrations.AddField(
            model_name='scheduledwish',
            name='retry_count',
            field=models.IntegerField(default=0, verbose_name='Retry Count'),
        ),
        migrations.AddField(
            model_name='scheduledwish',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sent At'),
        ),
        migrations.AddField(
            model_name='scheduledwish',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Celery Task ID'),
        ),
        migrations.AddField(
            model_name='scheduledwish',
            name='tone',
            field=models.CharField(default='Friendly', max_length=50, verbose_name='Tone'),
        ),
        migrations.AlterField(
            model_name='scheduledwish',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='scheduledwish',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='scheduledwish',
            name='message',
            field=models.TextField(blank=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='scheduledwish',
            name='occasion',
            field=models.CharField(choices=[('Birthday', 'Birthday'), ('Anniversary', 'Anniversary'), ('Festival', 'Festival'), ('Holiday', 'Holiday'), ('Custom', 'Custom')], default='Birthday', max_length=50, verbose_name='Occasion'),
        ),
        migrations.AlterField(
            model_name='scheduledwish',
            name='reminder_minutes',
            field=models.IntegerField(default=15, verbose_name='Reminder Minutes'),
        ),
        migrations.AlterField(
            model_name='scheduledwish',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Sent', 'Sent'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='scheduledwish',
            name='template',
            field=models.CharField(blank=True, max_length=100, verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='scheduledwish',
            name='time',
            field=models.TimeField(verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='scheduledwish',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=50, verbose_name='Timezone'),
        ),
        migrations.AlterField(
            model_name='scheduledwish',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_wishes_by_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='scheduledwish',
            index=models.Index(fields=['time'], name='core_schedu_time_5196c1_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledwish',
            index=models.Index(fields=['created_at'], name='core_schedu_created_2911c4_idx'),
        ),
    ]
