# Generated by Django 5.1.4 on 2026-07-12 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_core_schedu_contact_b15b3e_idx_core_schedu_contact_155163_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GreetingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Card', max_length=200)),
                ('occasion', models.CharField(choices=[('Birthday', 'Birthday'), ('Anniversary', 'Anniversary'), ('Wedding', 'Wedding'), ('Festival', 'Festival'), ('Christmas', 'Christmas'), ('NewYear', 'New Year'), ('Diwali', 'Diwali'), ('Eid', 'Eid'), ('Ramadan', 'Ramadan'), ('Valentine', 'Valentine'), ('MothersDay', "Mother's Day"), ('FathersDay', "Father's Day"), ('FriendshipDay', 'Friendship Day'), ('Graduation', 'Graduation'), ('Congratulations', 'Congratulations'), ('Custom', 'Custom')], default='Birthday', max_length=50)),
                ('recipient_name', models.CharField(blank=True, max_length=150)),
                ('heading', models.CharField(blank=True, max_length=300)),
                ('message', models.TextField(blank=True)),
                ('footer', models.CharField(blank=True, max_length=300)),
                ('signature', models.CharField(blank=True, max_length=150)),
                ('card_size', models.CharField(choices=[('instagram_square', 'Instagram Square (1080×1080)'), ('portrait', 'Portrait (1080×1350)'), ('landscape', 'Landscape (1920×1080)'), ('story', 'Story (1080×1920)'), ('email_banner', 'Email Banner (600×200)'), ('a5', 'A5 (1748×2480)'), ('custom', 'Custom')], default='instagram_square', max_length=30)),
                ('card_theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('gradient', 'Gradient'), ('glass', 'Glass')], default='dark', max_length=20)),
                ('card_width', models.IntegerField(default=500)),
                ('card_height', models.IntegerField(default=500)),
                ('background_color', models.CharField(default='#1a1a2e', max_length=50)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='greeting_cards/backgrounds/')),
                ('background_blur', models.IntegerField(default=0)),
                ('background_opacity', models.FloatField(default=1.0)),
                ('border_radius', models.IntegerField(default=16)),
                ('shadow', models.BooleanField(default=True)),
                ('font_family', models.CharField(default='Inter', max_length=100)),
                ('font_size', models.IntegerField(default=16)),
                ('font_color', models.CharField(default='#ffffff', max_length=50)),
                ('text_style', models.JSONField(blank=True, default=dict)),
                ('uploaded_photo', models.ImageField(blank=True, null=True, upload_to='greeting_cards/photos/')),
                ('elements_json', models.JSONField(blank=True, default=list)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='greeting_cards/previews/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='greeting_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Greeting Card',
                'verbose_name_plural': 'Greeting Cards',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='scheduledwish',
            name='greeting_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_wishes', to='core.greetingcard', verbose_name='Greeting Card'),
        ),
        migrations.CreateModel(
            name='GreetingCardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('occasion', models.CharField(choices=[('Birthday', 'Birthday'), ('Anniversary', 'Anniversary'), ('Wedding', 'Wedding'), ('Festival', 'Festival'), ('Christmas', 'Christmas'), ('NewYear', 'New Year'), ('Diwali', 'Diwali'), ('Eid', 'Eid'), ('Ramadan', 'Ramadan'), ('Valentine', 'Valentine'), ('MothersDay', "Mother's Day"), ('FathersDay', "Father's Day"), ('FriendshipDay', 'Friendship Day'), ('Graduation', 'Graduation'), ('Congratulations', 'Congratulations'), ('Custom', 'Custom')], default='Birthday', max_length=50)),
                ('category', models.CharField(choices=[('Minimal', 'Minimal'), ('Modern', 'Modern'), ('Cute', 'Cute'), ('Luxury', 'Luxury'), ('Corporate', 'Corporate'), ('Kids', 'Kids'), ('Floral', 'Floral'), ('Dark', 'Dark'), ('Classic', 'Classic'), ('AIGenerated', 'AI Generated')], default='Modern', max_length=50)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='card_templates/thumbnails/')),
                ('background_color', models.CharField(default='#1a1a2e', max_length=50)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='card_templates/backgrounds/')),
                ('elements_json', models.JSONField(blank=True, default=list, help_text='Array of element objects (text, image, emoji, shape)')),
                ('card_width', models.IntegerField(default=500)),
                ('card_height', models.IntegerField(default=500)),
                ('premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Greeting Card Template',
                'verbose_name_plural': 'Greeting Card Templates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['occasion'], name='core_greeti_occasio_7bb5f5_idx'), models.Index(fields=['category'], name='core_greeti_categor_c42f85_idx'), models.Index(fields=['is_active'], name='core_greeti_is_acti_71335d_idx')],
            },
        ),
        migrations.AddField(
            model_name='greetingcard',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards_using_template', to='core.greetingcardtemplate'),
        ),
        migrations.CreateModel(
            name='GreetingCardFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='core.greetingcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Greeting Card Favorite',
                'verbose_name_plural': 'Greeting Card Favorites',
                'unique_together': {('user', 'card')},
            },
        ),
        migrations.AddIndex(
            model_name='greetingcard',
            index=models.Index(fields=['user', 'status'], name='core_greeti_user_id_4f2dc7_idx'),
        ),
        migrations.AddIndex(
            model_name='greetingcard',
            index=models.Index(fields=['user', 'is_favorite'], name='core_greeti_user_id_a1e233_idx'),
        ),
        migrations.AddIndex(
            model_name='greetingcard',
            index=models.Index(fields=['occasion'], name='core_greeti_occasio_1fd8fd_idx'),
        ),
        migrations.AddIndex(
            model_name='greetingcard',
            index=models.Index(fields=['updated_at'], name='core_greeti_updated_207fcc_idx'),
        ),
    ]
