# Generated by Django 5.1.4 on 2026-07-17 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_greetingcard_scheduledwish_greeting_card_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='greetingcard',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='greeting_cards', to='core.contact'),
        ),
        migrations.CreateModel(
            name='SentGreetingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(default='Sent', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_greeting_cards', to='core.contact')),
                ('greeting_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_greeting_cards', to='core.greetingcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_greeting_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sent Greeting Card',
                'verbose_name_plural': 'Sent Greeting Cards',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['user'], name='core_sentgr_user_id_558b0c_idx'), models.Index(fields=['contact'], name='core_sentgr_contact_793bf9_idx')],
            },
        ),
    ]
