# Generated by Django 5.1.4 on 2026-07-17 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_greetingcard_contact_sentgreetingcard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SentAIGreeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting_text', models.TextField()),
                ('occasion', models.CharField(max_length=50)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(default='Sent', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_ai_greetings', to='core.contact')),
                ('generated_greeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.generatedgreeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_ai_greetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sent AI Greeting',
                'verbose_name_plural': 'Sent AI Greetings',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['user'], name='core_sentai_user_id_a4397f_idx'), models.Index(fields=['contact'], name='core_sentai_contact_315034_idx')],
            },
        ),
    ]
