# Generated by Django 5.1.4 on 2026-08-10 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_greetingcardtemplate_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CONTACT_CREATED', 'Contact Created'), ('CONTACT_UPDATED', 'Contact Updated'), ('CONTACT_DELETED', 'Contact Deleted'), ('EVENT_CREATED', 'Event Created'), ('EVENT_UPDATED', 'Event Updated'), ('EVENT_DELETED', 'Event Deleted'), ('WISH_GENERATED', 'Wish Generated'), ('WISH_SCHEDULED', 'Wish Scheduled'), ('WISH_SENT', 'Wish Sent'), ('WISH_FAILED', 'Wish Failed'), ('AI_GREETING_GENERATED', 'AI Greeting Generated'), ('GREETING_CARD_CREATED', 'Greeting Card Created'), ('GREETING_CARD_SENT', 'Greeting Card Sent'), ('SUBSCRIPTION_UPDATED', 'Subscription Updated')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='greetingcardtemplate',
            options={'ordering': ['sort_order', '-created_at'], 'verbose_name': 'Greeting Card Template', 'verbose_name_plural': 'Greeting Card Templates'},
        ),
        migrations.RenameIndex(
            model_name='greetingcardtemplate',
            new_name='core_greeti_is_prem_b15e88_idx',
            old_name='core_greeti_is_prem_9f3a21_idx',
        ),
        migrations.RenameIndex(
            model_name='greetingcardtemplate',
            new_name='core_greeti_is_feat_634213_idx',
            old_name='core_greeti_is_feat_a1c2b3_idx',
        ),
        migrations.RenameIndex(
            model_name='greetingcardtemplate',
            new_name='core_greeti_sort_or_2c75b1_idx',
            old_name='core_greeti_sort_o_7d4e5f_idx',
        ),
        migrations.RenameIndex(
            model_name='greetingcardtemplate',
            new_name='core_greeti_slug_acef64_idx',
            old_name='core_greeti_slug_b6c7d8_idx',
        ),
        migrations.AlterField(
            model_name='greetingcardtemplate',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='greeting_templates/background/'),
        ),
        migrations.AlterField(
            model_name='greetingcardtemplate',
            name='description',
            field=models.TextField(blank=True, help_text='Short marketing description shown in the gallery.'),
        ),
        migrations.AlterField(
            model_name='greetingcardtemplate',
            name='elements_json',
            field=models.JSONField(blank=True, default=list, help_text='Array of element objects (text, image, emoji, shape).'),
        ),
        migrations.AlterField(
            model_name='greetingcardtemplate',
            name='font_size',
            field=models.IntegerField(default=16, help_text='Base font size in px.'),
        ),
        migrations.AlterField(
            model_name='greetingcardtemplate',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Free-form key/value metadata.'),
        ),
        migrations.AlterField(
            model_name='greetingcardtemplate',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier (auto-generated from title if blank).', max_length=220, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='greetingcardtemplate',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Lower numbers appear first within a group.'),
        ),
        migrations.AlterField(
            model_name='greetingcardtemplate',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="List of string tags, e.g. ['romantic','gold']."),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'created_at'], name='core_activi_user_id_599332_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action_type'], name='core_activi_action__ba020b_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='core_activi_entity__fac333_idx'),
        ),
    ]
