# Generated by Django 5.1.4 on 2026-08-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_activitylog_alter_greetingcardtemplate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('CONTACT_CREATED', 'Contact Created'), ('CONTACT_UPDATED', 'Contact Updated'), ('CONTACT_DELETED', 'Contact Deleted'), ('EVENT_CREATED', 'Event Created'), ('EVENT_UPDATED', 'Event Updated'), ('EVENT_DELETED', 'Event Deleted'), ('WISH_GENERATED', 'Wish Generated'), ('WISH_SCHEDULED', 'Wish Scheduled'), ('WISH_SENT', 'Wish Sent'), ('WISH_CANCELLED', 'Wish Cancelled'), ('WISH_FAILED', 'Wish Failed'), ('AI_GREETING_GENERATED', 'AI Greeting Generated'), ('GREETING_CARD_CREATED', 'Greeting Card Created'), ('GREETING_CARD_UPDATED', 'Greeting Card Updated'), ('GREETING_CARD_SENT', 'Greeting Card Sent'), ('TEMPLATE_CREATED', 'Template Created'), ('TEMPLATE_UPDATED', 'Template Updated'), ('TEMPLATE_SAVED', 'Template Saved'), ('NOTIFICATION_CREATED', 'Notification Created'), ('SUBSCRIPTION_UPDATED', 'Subscription Updated')], max_length=50),
        ),
    ]
